---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ sentry__base_packages }}'
    - '{{ sentry__packages }}'

- name: Add sentry group
  group:
      name: '{{ sentry__group }}'
      state: present
      system: True

- name: Create sentry system user
  user:
    name: '{{ sentry__user }}'
    group: '{{ sentry__group }}'
    home: '{{ sentry__home }}'
    shell: '{{ sentry__shell }}'
    state: 'present'
    system: True

- name: Create directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: '{{ sentry__user }}'
    group: '{{ sentry__group }}'
    mode: '0755'
  with_items:
    - '{{ sentry__lib }}'
    - '/etc/sentry'

- name: Install sentry in a virtualenv
  pip:
    name:       '{{ item.name | d(item) }}'
    version:    '{{ item.version | d(omit) }}'
    virtualenv: '{{ sentry__virtualenv }}'
  become_user: '{{ sentry__user }}'
  with_flattened: '{{ sentry__virtualenv_pip_packages }}'
  register: sentry__register_virtualenv
  changed_when: (sentry__register_virtualenv|success and
                 sentry__register_virtualenv.stdout|search('New python executable in'))

- name: Copy config files
  template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
  with_items:
    - src: 'etc/sentry/sentry.conf.py.j2'
      dest: '/etc/sentry/sentry.conf.py'
    - src: 'etc/sentry/config.yml.j2'
      dest: '/etc/sentry/config.yml'
    - src: 'etc/systemd/system/sentry-web.service.j2'
      dest: '/etc/systemd/system/sentry-web.service'
    - src: 'etc/systemd/system/sentry-worker.service.j2'
      dest: '/etc/systemd/system/sentry-worker.service'
    - src: 'etc/systemd/system/sentry-cron.service.j2'
      dest: '/etc/systemd/system/sentry-cron.service'
  notify: Restart sentry services

- name: Enable sentry services
  service:
      name: '{{ item }}'
      enabled: yes
      state: restarted
  with_items:
    - sentry-web
    - sentry-worker
    - sentry-cron
  notify: Restart sentry services

- name: Initialize or migrate database
  command: /usr/local/bin/sentry --config /etc/sentry upgrade --noinput

# - name: Get email addresses of sentry users
#   sentryusers:
#     config: '/etc/sentry'
#   register: sentry_users

# TODO: This is not idempotent yet!!!!
- name: Create admin user
  command: |
    /usr/local/bin/sentry
      --config /etc/sentry createuser
      --email '{{ item }}'
      --password '{{ lookup("password", secret + "/credentials/" + ansible_fqdn + "/sentry/" + item + "/password length=" + sentry__superuser_password_length) }}'
      --superuser
      --no-input
  with_items: '{{ sentry__superusers }}'
  when: item not in sentry_users.emails


# Mailserver in config.yml (plus pw in conifg)

# SystemD autstart script in templates

# Redis bind to 127.0.1.1

# Redis slave read only disable
