---

- name: Manage Sentry service
  hosts: [ 'debops_service_sentry', 'debops_sentry' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list: '{{ sentry__apt_preferences__list }}'

    - role: debops.apt
      tags: [ 'role::apt' ]
      apt__sources: '{{ sentry__apt__sources }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_upstreams:
        - '{{ sentry__nginx_upstream }}'
      nginx_servers:
        - '{{ sentry__nginx_web_server }}'

    - role: debops.postgresql
      tags: [ 'role::sentry', 'depend::postgresql', 'depend::postgresql:sentry', 'depend-of::sentry', 'type::dependency' ]
      postgresql__roles: '{{ sentry__postgresql_roles }}'
      postgresql__databases:
        - '{{ sentry__postgresql_database }}'

    - role: ansible.sentry
      tags: [ 'role::sentry' ]
